export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const REGISTER_RECRUITER_BEGIN = 'REGISTER_RECRUITER_BEGIN'
export const REGISTER_RECRUITER_SUCCESS = 'REGISTER_RECRUITER_SUCCESS'
export const REGISTER_RECRUITER_ERROR = 'REGISTER_RECRUITER_ERROR'

export const LOGIN_RECRUITER_BEGIN = 'LOGIN_RECRUITER_BEGIN'
export const LOGIN_RECRUITER_SUCCESS = 'LOGIN_RECRUITER_SUCCESS'
export const LOGIN_RECRUITER_ERROR = 'LOGIN_RECRUITER_ERROR'

export const TOGGLE_SIDEBAR = 'TOOGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const UPDATE_RECRUITER_BEGIN = 'UPDATE_RECRUITER_BEGIN'
export const UPDATE_RECRUITER_SUCCESS = 'UPDATE_RECRUITER_SUCCESS'
export const UPDATE_RECRUITER_ERROR = 'UPDATE_RECRUITER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const POST_JOB_BEGIN = 'POST_JOB_BEGIN'
export const POST_JOB_SUCCESS = 'POST_JOB_SUCCESS'
export const POST_JOB_ERROR = 'POST_JOB_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const GET_OPPORTUNITIES_BEGIN = 'GET_OPPORTUNITIES_BEGIN'
export const GET_OPPORTUNITIES_SUCCESS = 'GET_OPPORTUNITIES_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'
